name: Frontend-ci

on:
  push:
    branches: ['master']

  pull_request :
    branches: ['master']

jobs:
  build-react:
    runs-on: ubuntu-latest

    env:
      VITE_API_URL:${{ secrets.VITE_API_URL }}
      VITE_RAZORPAY_KEY_ID:${{ secrets.VITE_RAZORPAY_KEY_ID }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version : 20
      
      - name: Install Dependencies
        run: npm install

      - name: Run Tests 
        run: npm test -- --watchAll=false
      
      - name: Build React
        run: npm run build



